apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "nifi.fullname" . }}
  labels:
    app: {{ template "nifi.name" . }}
    chart: {{ template "nifi.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "nifi.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "nifi.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: NIFI_WEB_HTTP_PORT
              value: {{ .Values.nifi.web.http.port | quote }}
            - name: NIFI_WEB_HTTP_HOST
              value: {{ .Values.nifi.web.http.host | quote }}
            - name: NIFI_WEB_HTTPS_PORT
              value: {{ .Values.nifi.web.https.port | quote }}
            - name: NIFI_WEB_HTTPS_HOST
              value: {{ .Values.nifi.web.https.host | quote }}
            - name: NIFI_REMOTE_INPUT_HOST
              value: {{ .Values.nifi.remote.input.host | quote }}
            - name: NIFI_REMOTE_INPUT_SOCKET_PORT
              value: {{ .Values.nifi.remote.input.socket.port | quote }}
          ports:
            - containerPort: {{ .Values.nifi.web.http.port }}
              protocol: TCP
              name: nifi-pod-http
            - containerPort: {{ .Values.nifi.web.https.port }}
              protocol: TCP
              name: nifi-pod-https
            - containerPort: {{ .Values.nifi.remote.input.socket.port }}
              protocol: TCP
              name: nifi-pod-socket
          readinessProbe:
            httpGet:
              path: /
              port: nifi-pod-http
              httpHeaders:
              - name: Host
                value: {{ .Values.nifi.web.http.host | quote }}
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: nifi-pod-http
              httpHeaders:
              - name: Host
                value: {{ .Values.nifi.web.http.port | quote }}
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
