apiVersion: v1
kind: Service
metadata:
  name: {{ template "nifi.fullname" . }}
  labels:
    app: {{ template "nifi.name" . }}
    chart: {{ template "nifi.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.nifi.web.http.port }}
      targetPort: http
      name: http
      protocol: TCP
    - port: {{ .Values.nifi.web.https.port }}
      targetPort: https
      name: https
      protocol: TCP
    - port: {{ .Values.nifi.remote.input.socket.port }}
      targetPort: socket
      name: socket
      protocol: TCP
  selector:
    app: {{ template "nifi.name" . }}
    release: {{ .Release.Name }}
